server:
  port: 8080
spring:
  application:
    name: orders-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:1111/eureka
